services:
  pdm:
    image: git.vichingo455.qzz.io/vichingo455/pdm:latest
    container_name: proxmox-datacenter-manager
    ports:
      - "8443:8443"
    volumes:
      - ./data:/var/lib/pdm
      - ./pdm-data:/var/lib/proxmox-datacenter-manager
      - ./config:/etc/proxmox-datacenter-manager
    hostname: pdm
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fkss", "https://localhost:8443/api2/json/version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s