services:
  pdm:
    image: git.vichingo455.com/vichingo455/pdm:latest
    container_name: proxmox-datacenter-manager
    ports:
      - "8443:8443"
    volumes:
      - ./data:/var/lib/pdm
      - ./pdm-data:/var/lib/proxmox-datacenter-manager
      - ./config:/etc/proxmox-datacenter-manager
    hostname: pdm
    restart: unless-stopped